version: "3.9"

services:

  app:
    container_name: coownershipmanager_app
    build:
      context: .
      dockerfile: app.Dockerfile 
      target: final
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - aspnet_keys:/root/.aspnet/

  db:
    container_name: coownershipmanager_db
    image: postgres:13.2-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./PostgresMigrations/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: CoOwnershipManager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret


  search:
   container_name: coownershipmanager_search
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node


volumes:
  db_data:
  aspnet_keys:
  elasticsearch-data:
